"""Candidate Pool Store — In-Memory & Persistent Collection of CandidateProfiles.

Consumes CandidateProfile objects generated by Version 1 ingestion and provides
fast indexing, candidate retrieval, attribute filtering, and candidate state tracking.
"""

import uuid
from typing import Dict, Any, List, Optional
from loguru import logger


class CandidatePoolStore:
    """Stores and indexes CandidateProfile objects in a searchable collection."""

    def __init__(self):
        self._pool: Dict[str, Dict[str, Any]] = {}

    def add_candidate(
        self,
        candidate_profile: Dict[str, Any],
        candidate_id: Optional[str] = None,
        doc_id: Optional[str] = None,
        filename: Optional[str] = None,
        status: str = "Unassigned"
    ) -> str:
        """Add a single candidate profile to the pool. Returns candidate_id."""
        cid = candidate_id or str(uuid.uuid4())[:8]

        def _pick_valid(prof: Dict[str, Any], key: str, fallback_keys: List[str]) -> str:
            val = prof.get(key)
            if val and isinstance(val, str) and val not in ("Not Mentioned", "Not Available", ""):
                return val
            for fk in fallback_keys:
                val = prof.get(fk)
                if val and isinstance(val, str) and val not in ("Not Mentioned", "Not Available", ""):
                    return val
            return "Not Mentioned"

        record = {
            "candidate_id": cid,
            "doc_id": doc_id or cid,
            "filename": filename or f"Candidate_{cid}.pdf",
            "candidate_profile": candidate_profile,
            "name": _pick_valid(candidate_profile, "name", ["candidate_name"]),
            "email": _pick_valid(candidate_profile, "email", []),
            "phone": _pick_valid(candidate_profile, "phone", []),
            "designation": _pick_valid(candidate_profile, "designation", []),
            "primary_domain": _pick_valid(candidate_profile, "primary_domain", ["domain"]),
            "total_experience": _pick_valid(candidate_profile, "total_experience", []),
            "current_location": _pick_valid(candidate_profile, "current_location", ["permanent_address", "address"]),
            "skills": candidate_profile.get("skills", []),
            "education": candidate_profile.get("education", []),
            "companies": candidate_profile.get("companies", []),
            "status": status,  # Unassigned, Shortlisted, Interviewing, On-Hold, Rejected
            "notes": ""
        }

        self._pool[cid] = record
        logger.info(f"Added candidate {cid} ({record['name']}) to CandidatePoolStore. Pool size: {len(self._pool)}")
        return cid

    def add_batch_candidates(self, candidate_profiles: List[Dict[str, Any]]) -> List[str]:
        """Batch add multiple candidate profiles (10 - 500+). Returns list of candidate_ids."""
        added_ids = []
        for item in candidate_profiles:
            profile = item.get("candidate_profile") or item
            doc_id = item.get("doc_id")
            filename = item.get("filename")
            cid = self.add_candidate(candidate_profile=profile, doc_id=doc_id, filename=filename)
            added_ids.append(cid)
        logger.info(f"Batch added {len(added_ids)} candidates to CandidatePoolStore. Total count: {len(self._pool)}")
        return added_ids

    def get_candidate(self, candidate_id: str) -> Optional[Dict[str, Any]]:
        """Retrieve candidate record by ID."""
        return self._pool.get(candidate_id)

    def get_profile(self, candidate_id: str) -> Optional[Dict[str, Any]]:
        """Retrieve CandidateProfile dictionary by ID."""
        record = self.get_candidate(candidate_id)
        return record.get("candidate_profile") if record else None

    def list_all(self) -> List[Dict[str, Any]]:
        """List all candidate records in the pool."""
        return list(self._pool.values())

    def list_all_candidates(self) -> List[Any]:
        """List all candidate records with attribute and dictionary access."""
        class _CandidateWrapper(dict):
            def __init__(self, data):
                super().__init__(data)
                self.__dict__ = self
            @property
            def candidate_name(self):
                return self.get("name") or self.get("candidate_name") or "Candidate"

        return [_CandidateWrapper(rec) for rec in self._pool.values()]

    def filter_candidates(
        self,
        domain: Optional[str] = None,
        skill: Optional[str] = None,
        location: Optional[str] = None,
        min_experience_years: Optional[float] = None,
        status: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Filter candidate pool by specific attributes."""
        results = []
        for record in self._pool.values():
            profile = record["candidate_profile"]

            if domain and domain.lower() not in record["primary_domain"].lower():
                continue

            if skill:
                sk_lower = skill.lower()
                all_skills = [s.lower() for s in record["skills"]]
                if not any(sk_lower in s for s in all_skills):
                    continue

            if location:
                loc_lower = location.lower()
                candidate_loc = (record["current_location"] or "").lower()
                if loc_lower not in candidate_loc:
                    continue

            if status and record["status"].lower() != status.lower():
                continue

            results.append(record)

        return results

    def update_status(self, candidate_id: str, new_status: str, notes: str = "") -> bool:
        """Update candidate workflow stage (Shortlisted, Interviewing, On-Hold, Rejected)."""
        record = self.get_candidate(candidate_id)
        if record:
            record["status"] = new_status
            if notes:
                record["notes"] = notes
            logger.info(f"Updated candidate {candidate_id} status to {new_status}")
            return True
        return False

    def remove_candidate(self, identifier: str) -> bool:
        """Remove a single candidate by candidate_id or doc_id."""
        to_delete = None
        for cid, rec in self._pool.items():
            if cid == identifier or rec.get("doc_id") == identifier or rec.get("candidate_id") == identifier:
                to_delete = cid
                break
        if to_delete and to_delete in self._pool:
            del self._pool[to_delete]
            logger.info(f"Removed candidate {to_delete} from CandidatePoolStore. Remaining pool size: {len(self._pool)}")
            return True
        return False

    def clear(self) -> None:
        """Clear all candidates from store."""
        self._pool.clear()
        logger.info("CandidatePoolStore cleared.")

    def count(self) -> int:
        """Return total candidate count."""
        return len(self._pool)


# Singleton Instance
candidate_pool_store = CandidatePoolStore()
