"""Recruiter Report Export Service — Export Candidate Pool Reports to CSV, Excel & PDF formats.
"""

import csv
import io
import json
from typing import Dict, Any, List, Optional
from loguru import logger


class RecruiterReportExportService:
    """Exports candidate scorecards, search results, and shortlists."""

    def export_to_csv(self, candidate_records: List[Dict[str, Any]]) -> str:
        """Export candidate list to CSV string."""
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            "Rank", "Candidate Name", "Email", "Phone", "Designation",
            "Domain", "Experience", "Location", "Overall Score (%)",
            "Suitability Tier", "Status"
        ])

        for idx, rec in enumerate(candidate_records):
            profile = rec.get("candidate_profile") or rec
            rank = rec.get("rank", idx + 1)
            name = rec.get("name") or rec.get("candidate_name") or profile.get("name", "N/A")
            email = rec.get("email") or profile.get("email", "N/A")
            phone = rec.get("phone") or profile.get("phone", "N/A")
            desig = rec.get("designation") or profile.get("designation", "N/A")
            domain = rec.get("primary_domain") or profile.get("primary_domain", "N/A")
            exp = rec.get("total_experience") or profile.get("total_experience", "0")
            loc = rec.get("current_location") or profile.get("current_location", "N/A")
            score = rec.get("overall_score", "N/A")
            tier = rec.get("suitability_tier", "N/A")
            status = rec.get("status", "Unassigned")

            writer.writerow([
                rank, name, email, phone, desig, domain, exp, loc, score, tier, status
            ])

        csv_content = output.getvalue()
        logger.info(f"Exported {len(candidate_records)} candidates to CSV format.")
        return csv_content

    def export_to_json(self, candidate_records: List[Dict[str, Any]]) -> str:
        """Export candidate list to JSON format."""
        return json.dumps(candidate_records, indent=2)

    def export_to_markdown_pdf(self, candidate_records: List[Dict[str, Any]], target_role: str = "Recruiter Pool") -> str:
        """Export candidate pool to printable Markdown report suitable for PDF rendering."""
        lines = [
            f"# AI Recruiter Platform V2 — Candidate Evaluation Report",
            f"**Target Role:** {target_role}",
            f"**Total Candidates Evaluated:** {len(candidate_records)}",
            "",
            "## Candidate Summary Table",
            "",
            "| Rank | Candidate Name | Designation | Experience | Location | Score | Suitability Tier | Status |",
            "|:---:|:---|:---|:---:|:---|:---:|:---|:---|"
        ]

        for idx, rec in enumerate(candidate_records):
            profile = rec.get("candidate_profile") or rec
            rank = rec.get("rank", idx + 1)
            name = rec.get("name") or rec.get("candidate_name") or profile.get("name", "N/A")
            desig = rec.get("designation") or profile.get("designation", "N/A")
            exp = rec.get("total_experience") or profile.get("total_experience", "0")
            loc = rec.get("current_location") or profile.get("current_location", "N/A")
            score = rec.get("overall_score", "N/A")
            tier = rec.get("suitability_tier", "N/A")
            status = rec.get("status", "Unassigned")

            lines.append(f"| {rank} | {name} | {desig} | {exp} | {loc} | {score}% | {tier} | {status} |")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by AI Recruiter Platform Version 2 Reasoner Engine*")

        report_md = "\n".join(lines)
        logger.info(f"Exported {len(candidate_records)} candidates to Markdown PDF format.")
        return report_md


# Singleton Instance
recruiter_report_export_service = RecruiterReportExportService()
